version: "3.9"

services:
  service:
    build:
      context: .
      dockerfile: service/Dockerfile
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
      - SERVICE_HOST=${SERVICE_HOST:-0.0.0.0}
      - SERVICE_PORT=${SERVICE_PORT:-8080}
      - SERVICE_HMAC_SECRET=${SERVICE_HMAC_SECRET}
      - HTTP_TIMEOUT_SECONDS=${HTTP_TIMEOUT_SECONDS:-20}
    ports:
      - "${SERVICE_PORT:-8080}:8080"
    volumes:
      - ./config:/app/config:ro
    healthcheck:
      test: ['CMD-SHELL', 'python -c "import urllib.request; urllib.request.urlopen(\'http://localhost:8080/health\')"']
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
      - BOT_TOKEN=${BOT_TOKEN}
      - SERVICE_BASE_URL=${SERVICE_BASE_URL:-http://service:8080}
      - SERVICE_HMAC_SECRET=${SERVICE_HMAC_SECRET}
      - DEFAULT_PROTOCOL=${DEFAULT_PROTOCOL:-vless}
      - DEFAULT_INBOUND_ID=${DEFAULT_INBOUND_ID:-1}
      - HTTP_TIMEOUT_SECONDS=${HTTP_TIMEOUT_SECONDS:-20}
    depends_on:
      service:
        condition: service_healthy
    volumes:
      - ./config:/app/config:ro
